descriptionFormat: '{product.title} - {title}'
handle: sneakerCompany
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: 'Sneakers Company'
productFieldLayouts:
  032a705a-fc0f-4fa6-810a-f39c5b7b3867:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            uid: bed3ba89-1c34-420e-9c13-443b117dc8fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 86d7e90c-733b-407b-9a96-cd35398a65f4 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a78a895c-64fb-40c6-8b7d-95c5880a89f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ec45d47-eaa5-4d38-9d88-c4ce0b2b49a4 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2250da12-310f-41df-9c5c-4e16d452aae9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: Variants
            required: false
            tip: null
            type: craft\commerce\fieldlayoutelements\VariantsField
            uid: 9281c6a3-5de0-4683-8df8-328ade6e8ac5
            userCondition: null
            warning: null
        name: Content
        uid: 1d2955bc-3c47-41df-9b8a-46934e7e8e31
        userCondition: null
productTitleFormat: ''
siteSettings:
  223fcb1f-bd7f-4c46-8ce6-d16a1e87a937: # test
    hasUrls: true
    template: ''
    uriFormat: 'sneaker-company/{slug}'
skuFormat: '{{ object.product.slug }}-{{ seq(object.product.slug) }}'
variantTitleFormat: '{product.title}'
