fieldLayouts:
  2435dc24-2c6c-417b-bdf3-bc381a8f7b27:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5f4c8a0a-3b79-4a3f-be45-2bf056572d1e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89bba26a-ee26-4ff5-bf73-9f9648b07164
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: ffb685f8-312e-4daf-b5c6-155813e70b51 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
