#!/bin/bash

# Usage:
# bash generateFonts

echo 'Enter Font to Transform. (ex. MyFont.ttf)'
read font
fontName=$(echo "$font" | cut -f 1 -d '.')

# Hint all fonts
pyftsubset "$font" --output-file="$fontName-hint-all.woff" --flavor=woff --layout-features="*" --unicodes=U+

pyftsubset "$font" --output-file="$fontName-hint-all.woff2" --flavor=woff2 --layout-features="*" --unicodes=U+0-10FFFF

pyftsubset "$font" --output-file="$fontName-kern-latin.woff" --flavor=woff --layout-features=ccmp,locl,mark,mkmk,kern --no-hinting --desubroutinize --unicodes=U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD

pyftsubset "$font" --output-file="$fontName-kern-latin.woff2" --flavor=woff2 --layout-features=ccmp,locl,mark,mkmk,kern --no-hinting --desubroutinize --unicodes=U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD
